<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_Hmi_Component" Id="{c3698ac7-38df-4291-b13c-14e193924f32}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT FB_Hmi_Component
VAR
	_initialized: BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Visibility" Id="{0496e00a-8a5c-4d8a-aed3-31bf6643fb00}">
      <Declaration><![CDATA[PROPERTY PUBLIC ABSTRACT Visibility : BOOL]]></Declaration>
      <Set Name="Set" Id="{1bdfbc8a-d582-499a-8c4d-b45e12663124}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>