<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_Hmi_Led" Id="{629fea12-c436-4ed1-9312-b78a6f33c585}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Hmi_Led
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Hmi_Led">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>